export const balanceSheetData = [
    {
        id: 1,
        accountCode: "AST-1001",
        accountName: "Cash in Hand",
        category: "Current Asset",
        amount: 250000,
        type: "Asset",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Cash available in office.",
    },
    {
        id: 2,
        accountCode: "AST-1002",
        accountName: "Bank Balance",
        category: "Current Asset",
        amount: 650000,
        type: "Asset",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Balance available in bank accounts.",
    },
    {
        id: 3,
        accountCode: "AST-1003",
        accountName: "Furniture & Fixtures",
        category: "Fixed Asset",
        amount: 180000,
        type: "Asset",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Office furniture and fixtures.",
    },
    {
        id: 4,
        accountCode: "LIA-1001",
        accountName: "Sundry Creditors",
        category: "Current Liability",
        amount: 210000,
        type: "Liability",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Outstanding supplier payments.",
    },
    {
        id: 5,
        accountCode: "EQT-1001",
        accountName: "Capital Account",
        category: "Equity",
        amount: 870000,
        type: "Equity",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Owner's capital invested in business.",
    },
];

export const defaultBalanceSheet = {
    accountCode: "",
    accountName: "",
    category: "Current Asset",
    amount: "",
    type: "Asset",
    financialYear: "2026-27",
    status: "Active",
    remarks: "",
};