export const creditNoteData = [
    {
        id: 1,
        voucherNo: "CN-1001",
        date: "04-07-2026",
        party: "ABC Traders",
        reference: "SAL-3001",
        reason: "Sales Return",
        amount: "₹12,500",
        status: "Approved",
        narration: "Customer returned damaged goods.",
    },
    {
        id: 2,
        voucherNo: "CN-1002",
        date: "03-07-2026",
        party: "Sharma Enterprises",
        reference: "SAL-2998",
        reason: "Rate Difference",
        amount: "₹8,900",
        status: "Draft",
        narration: "Rate adjustment issued.",
    },
    {
        id: 3,
        voucherNo: "CN-1003",
        date: "02-07-2026",
        party: "Global Industries",
        reference: "SAL-2986",
        reason: "Sales Return",
        amount: "₹15,200",
        status: "Approved",
        narration: "Returned excess quantity.",
    },
    {
        id: 4,
        voucherNo: "CN-1004",
        date: "01-07-2026",
        party: "Royal Distributors",
        reference: "SAL-2975",
        reason: "Discount Adjustment",
        amount: "₹5,400",
        status: "Pending",
        narration: "Additional discount provided.",
    },
    {
        id: 5,
        voucherNo: "CN-1005",
        date: "30-06-2026",
        party: "Bright Sales",
        reference: "SAL-2968",
        reason: "Sales Return",
        amount: "₹18,650",
        status: "Cancelled",
        narration: "Voucher cancelled.",
    },
];

export const defaultCreditNote = {
    voucherNo: "",
    date: "",
    party: "",
    reference: "",
    reason: "",
    amount: "",
    status: "Draft",
    narration: "",
};