// config/DebitNoteDummyData.js

export const debitNoteData = [
    {
        id: 1,
        voucherNo: "DN-1001",
        date: "04-07-2026",
        party: "ABC Traders",
        reference: "PUR-2001",
        reason: "Purchase Return",
        amount: "₹12,500",
        status: "Approved",
        narration: "Returned damaged goods.",
    },
    {
        id: 2,
        voucherNo: "DN-1002",
        date: "03-07-2026",
        party: "Sharma Enterprises",
        reference: "PUR-1998",
        reason: "Rate Difference",
        amount: "₹8,900",
        status: "Draft",
        narration: "Rate adjustment.",
    },
    {
        id: 3,
        voucherNo: "DN-1003",
        date: "02-07-2026",
        party: "Global Industries",
        reference: "PUR-1986",
        reason: "Short Supply",
        amount: "₹15,200",
        status: "Approved",
        narration: "Short quantity received.",
    },
    {
        id: 4,
        voucherNo: "DN-1004",
        date: "01-07-2026",
        party: "Royal Distributors",
        reference: "PUR-1975",
        reason: "Quality Issue",
        amount: "₹5,400",
        status: "Pending",
        narration: "Material quality issue.",
    },
    {
        id: 5,
        voucherNo: "DN-1005",
        date: "30-06-2026",
        party: "Bright Sales",
        reference: "PUR-1968",
        reason: "Purchase Return",
        amount: "₹18,650",
        status: "Cancelled",
        narration: "Voucher cancelled.",
    },
];

export const defaultDebitNote = {
    voucherNo: "",
    date: "",
    party: "",
    reference: "",
    reason: "",
    amount: "",
    status: "Draft",
    narration: "",
};