export const gstReportsData = [
    {
        id: 1,
        reportCode: "GST-1001",
        reportName: "GSTR-1",
        returnPeriod: "July 2026",
        gstType: "Outward Supplies",
        taxableValue: 850000,
        taxAmount: 153000,
        status: "Filed",
        filingDate: "2026-08-10",
        remarks: "Monthly outward supply return filed successfully.",
    },
    {
        id: 2,
        reportCode: "GST-1002",
        reportName: "GSTR-3B",
        returnPeriod: "July 2026",
        gstType: "Summary Return",
        taxableValue: 850000,
        taxAmount: 153000,
        status: "Filed",
        filingDate: "2026-08-20",
        remarks: "Monthly summary return submitted.",
    },
    {
        id: 3,
        reportCode: "GST-1003",
        reportName: "GSTR-2B",
        returnPeriod: "July 2026",
        gstType: "Input Tax Credit",
        taxableValue: 420000,
        taxAmount: 75600,
        status: "Generated",
        filingDate: "",
        remarks: "Auto-generated ITC statement.",
    },
    {
        id: 4,
        reportCode: "GST-1004",
        reportName: "GSTR-9",
        returnPeriod: "FY 2026-27",
        gstType: "Annual Return",
        taxableValue: 9800000,
        taxAmount: 1764000,
        status: "Pending",
        filingDate: "",
        remarks: "Annual GST return pending for filing.",
    },
    {
        id: 5,
        reportCode: "GST-1005",
        reportName: "GST Tax Summary",
        returnPeriod: "July 2026",
        gstType: "Tax Summary",
        taxableValue: 1270000,
        taxAmount: 228600,
        status: "Generated",
        filingDate: "",
        remarks: "Monthly GST tax summary generated.",
    },
];

export const defaultGstReport = {
    reportCode: "",
    reportName: "",
    returnPeriod: "",
    gstType: "Outward Supplies",
    taxableValue: "",
    taxAmount: "",
    status: "Pending",
    filingDate: "",
    remarks: "",
};