export const ledgerData = [
    {
        id: 1,
        voucherNo: "SAL-1001",
        date: "2026-07-01",
        accountName: "ABC Technologies",
        voucherType: "Sales",
        debit: 0,
        credit: 75000,
        balance: 75000,
        narration: "Sales invoice generated.",
        status: "Posted",
    },
    {
        id: 2,
        voucherNo: "REC-1001",
        date: "2026-07-02",
        accountName: "ABC Technologies",
        voucherType: "Receipt",
        debit: 50000,
        credit: 0,
        balance: 25000,
        narration: "Partial payment received.",
        status: "Posted",
    },
    {
        id: 3,
        voucherNo: "PUR-1001",
        date: "2026-07-03",
        accountName: "XYZ Suppliers",
        voucherType: "Purchase",
        debit: 45000,
        credit: 0,
        balance: 45000,
        narration: "Purchase of office equipment.",
        status: "Posted",
    },
    {
        id: 4,
        voucherNo: "PAY-1001",
        date: "2026-07-04",
        accountName: "XYZ Suppliers",
        voucherType: "Payment",
        debit: 0,
        credit: 20000,
        balance: 25000,
        narration: "Payment made via bank.",
        status: "Posted",
    },
    {
        id: 5,
        voucherNo: "JRN-1001",
        date: "2026-07-05",
        accountName: "Salary Expense",
        voucherType: "Journal",
        debit: 30000,
        credit: 0,
        balance: 30000,
        narration: "Monthly salary expense booked.",
        status: "Posted",
    },
];

export const defaultLedger = {
    voucherNo: "",
    date: "",
    accountName: "",
    voucherType: "Journal",
    debit: "",
    credit: "",
    balance: "",
    narration: "",
    status: "Posted",
};