export const materialIssueData = [
    {
        id: 1,
        issueNo: "MI-1001",
        issueDate: "2026-07-01",
        itemCode: "ITM-1001",
        itemName: "Laptop Dell Inspiron",
        warehouse: "Main Warehouse",
        issuedTo: "IT Department",
        quantity: 2,
        unit: "Nos",
        issueType: "Department",
        approvedBy: "Admin",
        status: "Issued",
        remarks: "Allocated to new employees.",
    },
    {
        id: 2,
        issueNo: "MI-1002",
        issueDate: "2026-07-02",
        itemCode: "ITM-1003",
        itemName: "Wireless Mouse",
        warehouse: "Main Warehouse",
        issuedTo: "Sales Department",
        quantity: 15,
        unit: "Nos",
        issueType: "Department",
        approvedBy: "Manager",
        status: "Issued",
        remarks: "Quarterly hardware distribution.",
    },
    {
        id: 3,
        issueNo: "MI-1003",
        issueDate: "2026-07-03",
        itemCode: "ITM-1004",
        itemName: "Mechanical Keyboard",
        warehouse: "Warehouse B",
        issuedTo: "Development Team",
        quantity: 8,
        unit: "Nos",
        issueType: "Project",
        approvedBy: "Project Lead",
        status: "Pending",
        remarks: "Awaiting approval.",
    },
    {
        id: 4,
        issueNo: "MI-1004",
        issueDate: "2026-07-04",
        itemCode: "ITM-1005",
        itemName: "27-inch Monitor",
        warehouse: "Main Warehouse",
        issuedTo: "Design Team",
        quantity: 5,
        unit: "Nos",
        issueType: "Department",
        approvedBy: "Admin",
        status: "Issued",
        remarks: "Workstation setup.",
    },
    {
        id: 5,
        issueNo: "MI-1005",
        issueDate: "2026-07-05",
        itemCode: "ITM-1002",
        itemName: "HP Laser Printer",
        warehouse: "Warehouse A",
        issuedTo: "Accounts Department",
        quantity: 1,
        unit: "Nos",
        issueType: "Office",
        approvedBy: "Finance Head",
        status: "Cancelled",
        remarks: "Issue request cancelled.",
    },
];

export const defaultMaterialIssue = {
    issueNo: "",
    issueDate: "",
    itemCode: "",
    itemName: "",
    warehouse: "",
    issuedTo: "",
    quantity: "",
    unit: "Nos",
    issueType: "",
    approvedBy: "",
    status: "Pending",
    remarks: "",
};