export const materialReceiveData = [
    {
        id: 1,
        receiveNo: "MR-1001",
        receiveDate: "2026-07-01",
        itemCode: "ITM-1001",
        itemName: "Laptop Dell Inspiron",
        warehouse: "Main Warehouse",
        receivedFrom: "ABC Technologies",
        quantity: 10,
        unit: "Nos",
        receiveType: "Purchase",
        receivedBy: "Store Manager",
        status: "Received",
        remarks: "Purchase order received successfully.",
    },
    {
        id: 2,
        receiveNo: "MR-1002",
        receiveDate: "2026-07-02",
        itemCode: "ITM-1003",
        itemName: "Wireless Mouse",
        warehouse: "Main Warehouse",
        receivedFrom: "XYZ Distributors",
        quantity: 50,
        unit: "Nos",
        receiveType: "Purchase",
        receivedBy: "Store Executive",
        status: "Received",
        remarks: "Monthly stock replenishment.",
    },
    {
        id: 3,
        receiveNo: "MR-1003",
        receiveDate: "2026-07-03",
        itemCode: "ITM-1004",
        itemName: "Mechanical Keyboard",
        warehouse: "Warehouse B",
        receivedFrom: "Production Unit",
        quantity: 20,
        unit: "Nos",
        receiveType: "Stock Transfer",
        receivedBy: "Warehouse Supervisor",
        status: "Pending",
        remarks: "Awaiting quality inspection.",
    },
    {
        id: 4,
        receiveNo: "MR-1004",
        receiveDate: "2026-07-04",
        itemCode: "ITM-1005",
        itemName: "27-inch Monitor",
        warehouse: "Main Warehouse",
        receivedFrom: "Display World Pvt Ltd",
        quantity: 12,
        unit: "Nos",
        receiveType: "Purchase",
        receivedBy: "Store Manager",
        status: "Received",
        remarks: "Received for workstation upgrade.",
    },
    {
        id: 5,
        receiveNo: "MR-1005",
        receiveDate: "2026-07-05",
        itemCode: "ITM-1002",
        itemName: "HP Laser Printer",
        warehouse: "Warehouse A",
        receivedFrom: "Head Office",
        quantity: 3,
        unit: "Nos",
        receiveType: "Stock Transfer",
        receivedBy: "Inventory Manager",
        status: "Cancelled",
        remarks: "Transfer request cancelled.",
    },
];

export const defaultMaterialReceive = {
    receiveNo: "",
    receiveDate: "",
    itemCode: "",
    itemName: "",
    warehouse: "",
    receivedFrom: "",
    quantity: "",
    unit: "Nos",
    receiveType: "",
    receivedBy: "",
    status: "Pending",
    remarks: "",
};