export const outstandingReportData = [
    {
        id: 1,
        reportCode: "OR-1001",
        reportName: "Customer Outstanding",
        reportType: "Receivable Report",
        partyType: "Customer",
        reportPeriod: "July 2026",
        totalParties: 145,
        totalOutstanding: 2850000,
        overdueAmount: 645000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Customer outstanding report generated successfully.",
    },
    {
        id: 2,
        reportCode: "OR-1002",
        reportName: "Vendor Outstanding",
        reportType: "Payable Report",
        partyType: "Vendor",
        reportPeriod: "July 2026",
        totalParties: 68,
        totalOutstanding: 1745000,
        overdueAmount: 285000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Vendor outstanding balance report.",
    },
    {
        id: 3,
        reportCode: "OR-1003",
        reportName: "Overdue Outstanding",
        reportType: "Overdue Report",
        partyType: "Customer",
        reportPeriod: "July 2026",
        totalParties: 24,
        totalOutstanding: 985000,
        overdueAmount: 985000,
        status: "Pending",
        generatedDate: "",
        remarks: "Outstanding invoices beyond due date.",
    },
    {
        id: 4,
        reportCode: "OR-1004",
        reportName: "Ageing Analysis",
        reportType: "Ageing Report",
        partyType: "All Parties",
        reportPeriod: "FY 2026-27",
        totalParties: 213,
        totalOutstanding: 4595000,
        overdueAmount: 1325000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Outstanding ageing analysis report.",
    },
    {
        id: 5,
        reportCode: "OR-1005",
        reportName: "Outstanding Summary",
        reportType: "Summary Report",
        partyType: "Customer & Vendor",
        reportPeriod: "July 2026",
        totalParties: 213,
        totalOutstanding: 4595000,
        overdueAmount: 930000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Consolidated outstanding summary report.",
    },
];

export const defaultOutstandingReport = {
    reportCode: "",
    reportName: "",
    reportType: "Summary Report",
    partyType: "",
    reportPeriod: "",
    totalParties: "",
    totalOutstanding: "",
    overdueAmount: "",
    status: "Pending",
    generatedDate: "",
    remarks: "",
};