export const profitLossData = [
    {
        id: 1,
        accountCode: "INC-1001",
        accountName: "Sales Revenue",
        category: "Direct Income",
        amount: 850000,
        type: "Income",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Revenue from product sales.",
    },
    {
        id: 2,
        accountCode: "INC-1002",
        accountName: "Service Income",
        category: "Indirect Income",
        amount: 120000,
        type: "Income",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Income from maintenance services.",
    },
    {
        id: 3,
        accountCode: "EXP-1001",
        accountName: "Purchase Expense",
        category: "Direct Expense",
        amount: 480000,
        type: "Expense",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Raw material purchases.",
    },
    {
        id: 4,
        accountCode: "EXP-1002",
        accountName: "Salary Expense",
        category: "Indirect Expense",
        amount: 180000,
        type: "Expense",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Monthly employee salaries.",
    },
    {
        id: 5,
        accountCode: "EXP-1003",
        accountName: "Electricity Expense",
        category: "Indirect Expense",
        amount: 25000,
        type: "Expense",
        financialYear: "2026-27",
        status: "Active",
        remarks: "Office electricity charges.",
    },
];

export const defaultProfitLoss = {
    accountCode: "",
    accountName: "",
    category: "Direct Income",
    amount: "",
    type: "Income",
    financialYear: "2026-27",
    status: "Active",
    remarks: "",
};