export const stockJournalData = [
    {
        id: 1,
        voucherNo: "SJ-0001",
        date: "2026-07-01",
        itemCode: "ITM-1001",
        itemName: "Laptop Dell Inspiron",
        fromWarehouse: "Main Warehouse",
        toWarehouse: "Warehouse A",
        quantity: 10,
        unit: "Nos",
        rate: 52000,
        amount: 520000,
        reason: "Internal Stock Transfer",
        status: "Completed",
        remarks: "Transferred for branch requirement.",
    },
    {
        id: 2,
        voucherNo: "SJ-0002",
        date: "2026-07-02",
        itemCode: "ITM-1002",
        itemName: "HP Laser Printer",
        fromWarehouse: "Warehouse A",
        toWarehouse: "Service Warehouse",
        quantity: 3,
        unit: "Nos",
        rate: 18000,
        amount: 54000,
        reason: "Repair Stock",
        status: "Completed",
        remarks: "Sent for servicing.",
    },
    {
        id: 3,
        voucherNo: "SJ-0003",
        date: "2026-07-03",
        itemCode: "ITM-1003",
        itemName: "Wireless Mouse",
        fromWarehouse: "Main Warehouse",
        toWarehouse: "Warehouse B",
        quantity: 50,
        unit: "Nos",
        rate: 550,
        amount: 27500,
        reason: "Stock Reallocation",
        status: "Pending",
        remarks: "Awaiting approval.",
    },
    {
        id: 4,
        voucherNo: "SJ-0004",
        date: "2026-07-04",
        itemCode: "ITM-1004",
        itemName: "Mechanical Keyboard",
        fromWarehouse: "Warehouse B",
        toWarehouse: "Main Warehouse",
        quantity: 15,
        unit: "Nos",
        rate: 2500,
        amount: 37500,
        reason: "Inventory Adjustment",
        status: "Completed",
        remarks: "Stock correction.",
    },
    {
        id: 5,
        voucherNo: "SJ-0005",
        date: "2026-07-05",
        itemCode: "ITM-1005",
        itemName: "27-inch Monitor",
        fromWarehouse: "Main Warehouse",
        toWarehouse: "Showroom",
        quantity: 8,
        unit: "Nos",
        rate: 14500,
        amount: 116000,
        reason: "Display Stock",
        status: "Completed",
        remarks: "Moved for showroom display.",
    },
];

export const defaultStockJournal = {
    voucherNo: "",
    date: "",
    itemCode: "",
    itemName: "",
    fromWarehouse: "",
    toWarehouse: "",
    quantity: "",
    unit: "Nos",
    rate: "",
    amount: "",
    reason: "",
    status: "Pending",
    remarks: "",
};