export const stockReportsData = [
    {
        id: 1,
        reportCode: "SR-1001",
        reportName: "Stock Summary",
        reportType: "Summary Report",
        warehouse: "Main Warehouse",
        reportPeriod: "July 2026",
        totalItems: 245,
        totalQuantity: 12850,
        stockValue: 3850000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Monthly stock summary generated successfully.",
    },
    {
        id: 2,
        reportCode: "SR-1002",
        reportName: "Stock Ledger",
        reportType: "Ledger Report",
        warehouse: "Warehouse A",
        reportPeriod: "July 2026",
        totalItems: 180,
        totalQuantity: 9450,
        stockValue: 2745000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Item-wise stock movement report.",
    },
    {
        id: 3,
        reportCode: "SR-1003",
        reportName: "Low Stock Report",
        reportType: "Inventory Alert",
        warehouse: "Warehouse B",
        reportPeriod: "July 2026",
        totalItems: 18,
        totalQuantity: 145,
        stockValue: 86500,
        status: "Pending",
        generatedDate: "",
        remarks: "Items below minimum stock level.",
    },
    {
        id: 4,
        reportCode: "SR-1004",
        reportName: "Stock Valuation",
        reportType: "Valuation Report",
        warehouse: "All Warehouses",
        reportPeriod: "FY 2026-27",
        totalItems: 420,
        totalQuantity: 21450,
        stockValue: 9685000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Closing stock valuation report.",
    },
    {
        id: 5,
        reportCode: "SR-1005",
        reportName: "Dead Stock Report",
        reportType: "Inactive Inventory",
        warehouse: "Main Warehouse",
        reportPeriod: "July 2026",
        totalItems: 12,
        totalQuantity: 220,
        stockValue: 148000,
        status: "Generated",
        generatedDate: "2026-07-31",
        remarks: "Items with no movement during selected period.",
    },
];

export const defaultStockReport = {
    reportCode: "",
    reportName: "",
    reportType: "Summary Report",
    warehouse: "",
    reportPeriod: "",
    totalItems: "",
    totalQuantity: "",
    stockValue: "",
    status: "Pending",
    generatedDate: "",
    remarks: "",
};