export const stockData = [
    {
        id: 1,
        itemCode: "ITM-1001",
        itemName: "Laptop Dell Inspiron",
        warehouse: "Main Warehouse",
        unit: "Nos",
        openingStock: 50,
        inward: 20,
        outward: 15,
        closingStock: 55,
        status: "In Stock",
        remarks: "New stock received.",
    },
    {
        id: 2,
        itemCode: "ITM-1002",
        itemName: "HP Laser Printer",
        warehouse: "Warehouse A",
        unit: "Nos",
        openingStock: 25,
        inward: 10,
        outward: 8,
        closingStock: 27,
        status: "In Stock",
        remarks: "Regular sales.",
    },
    {
        id: 3,
        itemCode: "ITM-1003",
        itemName: "Wireless Mouse",
        warehouse: "Main Warehouse",
        unit: "Nos",
        openingStock: 100,
        inward: 50,
        outward: 120,
        closingStock: 30,
        status: "Low Stock",
        remarks: "Reorder required.",
    },
    {
        id: 4,
        itemCode: "ITM-1004",
        itemName: "Mechanical Keyboard",
        warehouse: "Warehouse B",
        unit: "Nos",
        openingStock: 40,
        inward: 0,
        outward: 40,
        closingStock: 0,
        status: "Out of Stock",
        remarks: "Awaiting supplier.",
    },
    {
        id: 5,
        itemCode: "ITM-1005",
        itemName: "27-inch Monitor",
        warehouse: "Main Warehouse",
        unit: "Nos",
        openingStock: 35,
        inward: 15,
        outward: 10,
        closingStock: 40,
        status: "In Stock",
        remarks: "Stock updated.",
    },
];

export const defaultStock = {
    itemCode: "",
    itemName: "",
    warehouse: "",
    unit: "Nos",
    openingStock: "",
    inward: "",
    outward: "",
    closingStock: "",
    status: "In Stock",
    remarks: "",
};