export const trialBalanceData = [
    {
        id: 1,
        accountCode: "ACC-1001",
        accountName: "Cash in Hand",
        accountGroup: "Current Assets",
        openingDebit: 50000,
        openingCredit: 0,
        debit: 120000,
        credit: 85000,
        closingDebit: 85000,
        closingCredit: 0,
        status: "Balanced",
    },
    {
        id: 2,
        accountCode: "ACC-1002",
        accountName: "Bank Account",
        accountGroup: "Bank Accounts",
        openingDebit: 150000,
        openingCredit: 0,
        debit: 200000,
        credit: 180000,
        closingDebit: 170000,
        closingCredit: 0,
        status: "Balanced",
    },
    {
        id: 3,
        accountCode: "ACC-1003",
        accountName: "ABC Technologies",
        accountGroup: "Sundry Debtors",
        openingDebit: 30000,
        openingCredit: 0,
        debit: 75000,
        credit: 50000,
        closingDebit: 55000,
        closingCredit: 0,
        status: "Balanced",
    },
    {
        id: 4,
        accountCode: "ACC-1004",
        accountName: "XYZ Suppliers",
        accountGroup: "Sundry Creditors",
        openingDebit: 0,
        openingCredit: 45000,
        debit: 20000,
        credit: 60000,
        closingDebit: 0,
        closingCredit: 85000,
        status: "Balanced",
    },
    {
        id: 5,
        accountCode: "ACC-1005",
        accountName: "Sales Account",
        accountGroup: "Direct Income",
        openingDebit: 0,
        openingCredit: 0,
        debit: 0,
        credit: 350000,
        closingDebit: 0,
        closingCredit: 350000,
        status: "Balanced",
    },
];

export const defaultTrialBalance = {
    accountCode: "",
    accountName: "",
    accountGroup: "",
    openingDebit: "",
    openingCredit: "",
    debit: "",
    credit: "",
    closingDebit: "",
    closingCredit: "",
    status: "Balanced",
};