export const usersData = [
    {
        id: 1,
        userCode: "USR-1001",
        fullName: "Rohit Sharma",
        username: "rohit.sharma",
        email: "rohit.sharma@example.com",
        mobile: "+91 9876543210",
        role: "Administrator",
        department: "Administration",
        designation: "System Admin",
        status: "Active",
        lastLogin: "2026-07-07 09:30 AM",
        createdDate: "2026-01-10",
        remarks: "Primary system administrator.",
    },
    {
        id: 2,
        userCode: "USR-1002",
        fullName: "Priya Verma",
        username: "priya.verma",
        email: "priya.verma@example.com",
        mobile: "+91 9876543211",
        role: "Accountant",
        department: "Accounts",
        designation: "Senior Accountant",
        status: "Active",
        lastLogin: "2026-07-06 05:15 PM",
        createdDate: "2026-02-18",
        remarks: "Handles accounting and finance operations.",
    },
    {
        id: 3,
        userCode: "USR-1003",
        fullName: "Amit Kumar",
        username: "amit.kumar",
        email: "amit.kumar@example.com",
        mobile: "+91 9876543212",
        role: "Sales Manager",
        department: "Sales",
        designation: "Manager",
        status: "Inactive",
        lastLogin: "2026-06-28 11:10 AM",
        createdDate: "2026-03-05",
        remarks: "Sales department manager.",
    },
    {
        id: 4,
        userCode: "USR-1004",
        fullName: "Neha Singh",
        username: "neha.singh",
        email: "neha.singh@example.com",
        mobile: "+91 9876543213",
        role: "Inventory Executive",
        department: "Inventory",
        designation: "Executive",
        status: "Active",
        lastLogin: "2026-07-07 08:45 AM",
        createdDate: "2026-04-12",
        remarks: "Responsible for inventory management.",
    },
    {
        id: 5,
        userCode: "USR-1005",
        fullName: "Vikas Mehta",
        username: "vikas.mehta",
        email: "vikas.mehta@example.com",
        mobile: "+91 9876543214",
        role: "Purchase Officer",
        department: "Purchase",
        designation: "Officer",
        status: "Suspended",
        lastLogin: "2026-06-20 03:40 PM",
        createdDate: "2026-05-08",
        remarks: "User account temporarily suspended.",
    },
];

export const defaultUser = {
    userCode: "",
    fullName: "",
    username: "",
    email: "",
    mobile: "",
    password: "",
    role: "",
    department: "",
    designation: "",
    status: "Active",
    lastLogin: "",
    createdDate: "",
    remarks: "",
};